### ISSUE TITLE
documentation missing about usage, declare, and configure tasks

### ISSUE THREAD

**Issue by dsyleixa** [Robokishan/Arduino-Scheduler#2]
hello,
could you please provide more documentations about usage, declare, and configure tasks?
And as to long time-consuming computations, how to "yield" intermediately to either other tasks (i.e., intermittent computation  interruption and later resumption at the old computation point)?
Additionally, for which board cores is the lib suitable (AVR, SAMD21, SAMD51, SAM3X, ESP8266)?

**Comment by Robokishan** [comment]
Hey yes i am working on the documentation side. Bdw have you tried to run example code ?

This library is probably supported in all the hardware where c is supported since there are no hal level code is involved.
I will add documentation and how to use it in details very soon . Thanks you for the interest

**Comment by Robokishan** [comment]
I have updated the docs can you please check that out

**Comment by dsyleixa** [comment]
thank you, I meanwhile looked through it and read your docs, but the syntax is a bit too complicated for my skills and purposes. 
I am already working with multithreading programs very successfully on my Raspeberry Pi (both with C pthread + mutex + thread prios and also with C++ std::thread), and even with my ESP32 std::thread is working quite OK (Espressif RTOS-based libs, with some drawbacks admittedly), and for the rest of my Arduinos (Mega, Due, SAMD21, SAMD51) I would need also a compatible syntax like pthread or std::thread. But thank you very much for your reply!

**Comment by dsyleixa** [comment]
thank you, I meanwhile looked through it and read your docs, but the syntax is a bit too complicated for my skills and purposes.
I am already working with multithreading programs very successfully on my Raspeberry Pi (both with C pthread + mutex + thread prios and also with C++ std::thread), and even with my ESP32 std::thread is working quite OK (RTOS-based libs, with some drawbacks admittedly), and for the rest of my Arduinos (Mega, Due, SAMD21, SAMD51 and perhaps my ESP8266) I would need also a compatible syntax like pthread or std::thread.  Additionally, it's essential to have pre-emptive multithreading, not just a  cooperative one.
But thank you very much for your reply!

**Comment by Robokishan** [comment]
Yes. It's not a threading library. It's more like a scheduler where you can schedule a function at certain frequency without using delay. For sufficiently
